spring.application.name=mahi

# ডাটাবেস ইউআরএল (এখানে noboghat_db নামে একটি ডাটাবেস আগে থেকেই XAMPP-এর phpMyAdmin-এ তৈরি)
spring.datasource.url=jdbc:mysql://localhost:3306/noboghat_db
spring.datasource.username=root
spring.datasource.password=

# Hibernate সেটিংস (এটি আপনার Java ক্লাস থেকে ডাটাবেস টেবিল অটোমেটিক তৈরি করবে)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true